//
// Generated file, do not edit! Created by opp_msgtool 6.3 from src/messages/ControlMessages.msg.
//

#ifndef __CONTROLMESSAGES_M_H
#define __CONTROLMESSAGES_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class NetworkStateReport;
class ControlDecision;
/**
 * Class generated from <tt>src/messages/ControlMessages.msg:2</tt> by opp_msgtool.
 * <pre>
 * message NetworkStateReport
 * {
 *     string reporter;
 *     string linkId;
 *     double utilization;
 *     int queueLength;
 *     double packetLossRate;
 *     bool failed;
 *     simtime_t measuredAt;
 * }
 * </pre>
 */
class NetworkStateReport : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string reporter;
    omnetpp::opp_string linkId;
    double utilization = 0;
    int queueLength = 0;
    double packetLossRate = 0;
    bool failed = false;
    omnetpp::simtime_t measuredAt = SIMTIME_ZERO;

  private:
    void copy(const NetworkStateReport& other);

  protected:
    bool operator==(const NetworkStateReport&) = delete;

  public:
    NetworkStateReport(const char *name=nullptr, short kind=0);
    NetworkStateReport(const NetworkStateReport& other);
    virtual ~NetworkStateReport();
    NetworkStateReport& operator=(const NetworkStateReport& other);
    virtual NetworkStateReport *dup() const override {return new NetworkStateReport(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getReporter() const;
    virtual void setReporter(const char * reporter);

    virtual const char * getLinkId() const;
    virtual void setLinkId(const char * linkId);

    virtual double getUtilization() const;
    virtual void setUtilization(double utilization);

    virtual int getQueueLength() const;
    virtual void setQueueLength(int queueLength);

    virtual double getPacketLossRate() const;
    virtual void setPacketLossRate(double packetLossRate);

    virtual bool getFailed() const;
    virtual void setFailed(bool failed);

    virtual omnetpp::simtime_t getMeasuredAt() const;
    virtual void setMeasuredAt(omnetpp::simtime_t measuredAt);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NetworkStateReport& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NetworkStateReport& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/messages/ControlMessages.msg:13</tt> by opp_msgtool.
 * <pre>
 * message ControlDecision
 * {
 *     string action;
 *     string target;
 *     string selectedPath;
 *     int priority;
 *     simtime_t issuedAt;
 * }
 * </pre>
 */
class ControlDecision : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string action;
    omnetpp::opp_string target;
    omnetpp::opp_string selectedPath;
    int priority = 0;
    omnetpp::simtime_t issuedAt = SIMTIME_ZERO;

  private:
    void copy(const ControlDecision& other);

  protected:
    bool operator==(const ControlDecision&) = delete;

  public:
    ControlDecision(const char *name=nullptr, short kind=0);
    ControlDecision(const ControlDecision& other);
    virtual ~ControlDecision();
    ControlDecision& operator=(const ControlDecision& other);
    virtual ControlDecision *dup() const override {return new ControlDecision(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getAction() const;
    virtual void setAction(const char * action);

    virtual const char * getTarget() const;
    virtual void setTarget(const char * target);

    virtual const char * getSelectedPath() const;
    virtual void setSelectedPath(const char * selectedPath);

    virtual int getPriority() const;
    virtual void setPriority(int priority);

    virtual omnetpp::simtime_t getIssuedAt() const;
    virtual void setIssuedAt(omnetpp::simtime_t issuedAt);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ControlDecision& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ControlDecision& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline NetworkStateReport *fromAnyPtr(any_ptr ptr) { return check_and_cast<NetworkStateReport*>(ptr.get<cObject>()); }
template<> inline ControlDecision *fromAnyPtr(any_ptr ptr) { return check_and_cast<ControlDecision*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CONTROLMESSAGES_M_H

